trigger:
- master

pool:
	vmImage: 'windows-latest'

variables:
	buildConfiguration: 'Release'
	outputDirectory: '$(Build.BinariesDirectory)/$(buildConfiguration)'

steps:
- task: CmdLine@2
	inputs:
		script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
	inputs:
		command: 'publish'
		publishWebProjects: false
		projects: 'MyMAUIProject.sln'
		arguments: '-c $(buildConfiguration) -f:net6.0-windows10.0.19041.0'
		zipAfterPublish: false
		modifyOutputPath: false

- task: PublishBuildArtifacts@1
	inputs:
		PathtoPublish: '$(Build.ArtifactStagingDirectory)'
		ArtifactName: 'drop'
		publishLocation: 'Container'
