name: .NET MAUI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ (contains(matrix.tfm, 'maccatalyst') && 'macos-12') || 'windows-latest' }}
    strategy:
      matrix:
        tfm: [net7.0-android, net7.0-ios, net7.0-maccatalyst, net7.0-windows10.0.19041.0]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore Alice_Novel/Alice_Novel.csproj

      - name: Build MAUI App
        run: dotnet build Alice_Novel/Alice_Novel.csproj -c Release -f ${{ matrix.tfm }} --no-restore -p:PublishReadyToRun=false
        # -p:PublishReadyToRun=false はWindowsの謎エラーの対策として追加。

      # Upload Artifact
      - name: Android Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: android-ci-build
          path: Alice_Novel/bin/Release/net7.0-android/*Signed.a*

      - name: iOS Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ios-ci-build
          path: Alice_Novel/bin/Release/net7.0-ios/**/*.app/

      - name: MacCatalyst Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: macos-ci-build
          path: Alice_Novel/bin/Release/net7.0-maccatalyst/**/*.app/

      - name: Windows Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: windows-ci-build
          path: Alice_Novel/bin/Release/net7.0-windows*/**/Alice_Novel*.msix

      - name: Full Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: full-ci-build
          path: Alice_Novel/bin/Release/${{ matrix.tfm }}*/
