name: .NET MAUI Build

on:
  push:
    branches: [ master ]
    paths:
      - 'src/AliceNovel/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/AliceNovel/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ${{ (contains(matrix.tfm, 'maccatalyst') && 'macos-latest') || 'windows-latest' }}
    strategy:
      matrix:
        tfm: [net8.0-android, net8.0-ios, net8.0-maccatalyst, net8.0-windows10.0.19041.0]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore AliceNovel/src/AliceNovel.csproj

      - name: Build MAUI App
        run: dotnet build AliceNovel/src/AliceNovel.csproj -c Release -f ${{ matrix.tfm }} --no-restore -p:PublishReadyToRun=false -p:WindowsPackageType=None

      # Upload Artifact
      - if: matrix.tfm == 'net8.0-android'
        name: Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-ci-build
          path: src/AliceNovel/bin/Release/net8.0-android/*Signed.a*

      - if: matrix.tfm == 'net8.0-ios'
        name: iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ci-build
          path: src/AliceNovel/bin/Release/net8.0-ios/**/*.app/

      - if: matrix.tfm == 'net8.0-maccatalyst'
        name: MacCatalyst Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-ci-build
          path: src/AliceNovel/bin/Release/net8.0-maccatalyst/**/*.app/

      - if: matrix.tfm == 'net8.0-windows10.0.19041.0'
        name: Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-ci-build
          path: src/AliceNovel/bin/Release/net8.0-windows*/**/

      - name: Full Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: full-ci-build
          path: src/AliceNovel/bin/Release/${{ matrix.tfm }}*/
